plugins:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
exclude_patterns:
  - ci/
  - vendor/
  - node_modules/
  - bower_components/
  - application/test/
  - application/third_party/
